# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the contents of the 'scripts' directory (including your Flask app) to the container's /app directory
COPY scripts/ /app/

# Copy the contents of the 'models' directory into the container's /app/models directory
COPY models/ /app/models/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Expose the port the app runs on (default for Flask is 5000)
EXPOSE 5000

# Define environment variables (Optional but can be helpful for Flask)
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development

# Run the application
CMD ["flask", "run"]
